% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name EDLC
%  @associatedFile /MATLAB Drive/EDLC.m
%  @mostRecentlyActioned true
%  @uniqueId B4B6A3A1

EDLC

%% @name eigs
%  @associatedFile /MATLAB Drive/eigs.m
%  @mostRecentlyActioned true
%  @uniqueId 89D60521

eigs

